### ISSUE TITLE
Reformat Some Data

### ISSUE THREAD

**Issue by jjpearson8611** [acswmu/cico-data-mining#1]
The data is currently in a not very helpful state to answer some questions. 
Data in the form of below would be good.
If a computer is used more than once we will want to keep them separate.
| Computer Name | Date Checked Out | Time Used on Date |

If you think of a better format feel free to chop it up.
Store data in the data section and we should create a new directory for file cleaning up.

**Comment by brndmfrd** [comment]
A sample of how the data will be kept would prove helpful. Will the data be stored in a flat file format? Will the data be stored in a database? Will the data be available via a distributed Cassandra database in a hadoop cluster? A small sample would be very helpful.

**Comment by jjpearson8611** [comment]
A database will probably be the best call. I don't know enough about the different flavors of NoSQL to know which would be best. This being said we do have a different team working on assembling a small cluster now (3-5 blade servers) so Cassandra could be a good choice if we would like to try and move it to a cluster. It looks like R has a package that makes using cassandra easy https://rforge.net/doc/packages/RCassandra/RCassandra.html.

As for data formatting a sample entry would take a check out and a check in and calculate time between. This is the total time that machine was used by that student.

For Example:
First we find a check out and its respective check in
| 6/26/2014 9:20 | CheckOut | a77 |
| 6/26/2014 9:42 | CheckIn  | a77 |

Calculate time used and what semester it is
| name | date used | time used in mins | Semester |
| a77 | 6/26/2014 | 22 | Summer II |

**Comment by brndmfrd** [comment]
Exciting! I have seen a lot of positive reactions from people who love Cassandra (and hadoop). 

As for check-out time-stamps, can we guarantee that a checkout will always occur as expected? Is it possible that a user could shut-down the machine and leave the station unattended while it is still logically checked-out? Additionally, can we guarantee the check-ins are accurate? Is is possible for duplicate check-ins of the same station to occur? 

It may be prudent to sanitize the data before any processing is done.
